<?php $_order = $this->getOrder() ?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Address') ?></h2>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-2">
        <?php else: ?>
        <div class="col-1">
            <?php endif; ?>
            <h2><?php echo $this->__('Billing Address') ?></h2>
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
        <?php if (!$_order->getIsVirtual()): ?>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <h2><?php echo $this->__('Shipping Method') ?></h2>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        </div>
        <?php endif; ?>
        <div class="col-2">
            <h2><?php echo $this->__('Payment Method') ?></h2>
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
    <h2><?php echo $this->__('Items Ordered') ?></h2>
    <table class="data-table" id="my-orders-table">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        </thead>
        <tfoot>
        <tr class="subtotal first">
            <td class="a-right" colspan="4"><?php echo $this->__('Subtotal')?></td>
            <td class="last a-right">
                <span class="price"><?php echo Mage::helper('core')->formatPrice($_order->getSubtotal())?></span>
            </td>
        </tr>
        <tr class="shipping">
            <td class="a-right" colspan="4"><?php echo $this->__('Shipping &amp; Handling')?></td>
            <td class="last a-right">
                <span class="price"><?php echo Mage::helper('core')->formatPrice($_order->getShippingAmount())?></span>
            </td>
        </tr>
        <tr class="tax">
            <td class="a-right" colspan="4"><?php echo $this->__('Tax')?></td>
            <td class="last a-right">
                <span class="price"><?php echo Mage::helper('core')->formatPrice($_order->getTaxAmount())?></span>
            </td>
        </tr>
        <tr class="grand_total last">
            <td class="a-right" colspan="4">
                <strong><?php echo $this->__('Grand Total')?></strong>
            </td>
            <td class="last a-right">
                <strong><span class="price"><?php echo Mage::helper('core')->formatPrice($_order->getGrandTotal())?></span></strong>
            </td>
        </tr>
        </tfoot>
        <?php $_items = $this->getOrderItems(); ?>
        <?php $_index = 0; ?>
        <?php $_count = $_items->count(); ?>
        <?php foreach ($_items as $_item): ?>
            <tbody>
                <tr class="border<?php echo ($_index++ > $_count ?' last':'') ?>" id="order-item-row-<?php echo $_item->getId() ?>">
                    <td>
                        <h3 class="product-name">
                            <?php echo $_item->getItemName()?>
                    </td>
                    <td data-rwd-label="SKU"><?php echo $_item->getItemSku() ?></td>
                    <td data-rwd-label="Price" class="a-right">
                        <span class="price-excl-tax">
                            <span class="cart-price">
                                <span class="price"><?php echo Mage::helper('core')->formatPrice($_item->getItemPrice())?></span>
                            </span>
                        </span>
                        <br>
                    </td>
                    <td data-rwd-label="Qty" class="a-right">
                        <span class="nobr">
                            <?php echo $this->__('Ordered')?>: <strong><?php echo $_item->getItemQtyOrdered()*1?></strong><br>
                        </span>
                    </td>
                    <td data-rwd-label="Subtotal" class="a-right last">
                    <span class="price-excl-tax">
                        <span class="cart-price">
                            <span class="price"><?php echo Mage::helper('core')->formatPrice($_item->getItemRowTotal()) ?></span>
                        </span>
                    </span>
                        <br>
                    </td>
                </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
    <script type="text/javascript">window.print();</script>